### ISSUE TITLE
The Ultimate Connection Guide (How-Tos)

### ISSUE THREAD

**Issue by manmeetkaur** [astronomer/docs#2272]
**Request type:**

- [ ] **New tutorial:**: Add the `docs-content` and `area/learn` labels to this issue.
- [ ] **New Airflow concept:**: Add the `docs-content` and `area/learn` label to this issue.
- [x] **Addition to an existing guide**: Add the `area-learn` and `enhancement` labels to this issue.

**Use case or feature that should be covered:** Connections via Airflow UI

**Who the guide is intended for:** Airflow Users - basically getting started with a new connection - and various ways to create it
e.g. users who are new to Airflow, users who are migrating from a legacy scheduler, etc.

**Are you the right person to review a draft of the guide for technical accuracy? If not, who is?** @juliana-astro @fritz-astronomer

**Comment by manmeetkaur** [comment]
Following Connections are being added in the first pass:
- Redshift
- Snowflake
- BigQuery
- Azure Data Lake
- Synapse
- Azure Blob Storage
- Postgres
- Databricks
- DBT
- SQL Server

**Comment by manmeetkaur** [comment]
Draft:
https://www.notion.so/astronomerio/Connections-dfcafbc17a594cab91701f6473ec2f82?pvs=4
