### ISSUE TITLE
Additional CI/CD Templates on Gen2 Cloud Docs

### ISSUE THREAD

**Issue by aspain** [astronomer/docs#346]
**Affected Document:**
https://docs.astronomer.io/cloud/ci-cd
**Problem Type (Priority):**

- [ ] Error (Critical): This document has existing information that's incorrect and prevents readers from completing the documented setup (Add the `error/critical` label to this issue)
- [X] Misleading (Important): This document could benefit from additional context, guidance, or clarity (Add the `error/FYI` label to this issue)
- [ ] Typo (Low): Any issue related to spelling/ punctuation/ formatting (Add the `error/typo` label to this issue)

**Suggested Change (include links to relevant existing docs, support tickets, messages, or external content):**
Currently the [Enterprise CI/CD Page ](https://docs.astronomer.io/enterprise/ci-cd) has many example templates while the Cloud page only has a GitHub Actions example. 

Often we are sharing the enterprise page w/ Cloud customers and mention that it should work the same - but it would be less confusing for customers to remain on the docs page for their deployment (cloud vs enterprise)

Can we copy the additional templates over to the cloud docs? Are there any differences between setting them up on Enterprise vs Cloud? 

**Additional Notes:**

**Comment by aspain** [comment]
I was able to confirm with customer **Chiper** that they were able to integrate Jenkins into their gen2 deployment with the following scripts:

**Jenkinsfile** at root directory:
```
pipeline {
 agent any
   stages {
     stage('Deploy to astronomer') {
       when {
        expression {
          return env.GIT_BRANCH == "origin/main"
        }
       }
       steps {
         script {
           sh "chmod +x -R ${env.WORKSPACE}"
           sh('./build.sh')
         }
       }
     }
   }
 post {
   always {
     cleanWs()
   }
 }
}
```

**build.sh** at the root directory:
```
# Create time stamp
TAG=deploy-`date "+%Y-%m-%d-%HT%M-%S"`

# Step 1. Use the Access token in the `astro auth login` command
docker login images.astronomer.cloud -u $ASTRONOMER_KEY_ID -p $ASTRONOMER_KEY_SECRET

# Step 2. Request the Organization Id

# Step 3. Build the image
docker build . -t images.astronomer.cloud/$ORGANIZATION_ID/$DEPLOYMENT_ID:$TAG

# Step 4. Push the image
docker push images.astronomer.cloud/$ORGANIZATION_ID/$DEPLOYMENT_ID:$TAG

# Step 5. Get the access token
echo "get token"
TOKEN=$( curl --location --request POST "https://auth.astronomer.io/oauth/token" \
        --header "content-type: application/json" \
        --data-raw "{
            \"client_id\": \"$ASTRONOMER_KEY_ID\",
            \"client_secret\": \"$ASTRONOMER_KEY_SECRET\",
            \"audience\": \"astronomer-ee\",
            \"grant_type\": \"client_credentials\"}" | jq -r '.access_token' )
# Step 6. Create the Image
echo "get image id"
IMAGE=$( curl --location --request POST "https://api.astronomer.io/hub/v1" \
        --header "Authorization: Bearer $TOKEN" \
        --header "Content-Type: application/json" \
        --data-raw "{
            \"query\" : \"mutation imageCreate(\n    \$input: ImageCreateInput!\n) {\n    imageCreate (\n    input: \$input\n) {\n    id\n    tag\n    repository\n    digest\n    env\n    labels\n    deploymentId\n  }\n}\",
            \"variables\" : {
                \"input\" : {
                    \"deploymentId\" : \"$DEPLOYMENT_ID\",
                    \"tag\" : \"$TAG\"
                    }
                }
            }" | jq -r '.data.imageCreate.id')
# Step 7. Deploy the Image
echo "deploy image"
curl --location --request POST "https://api.astronomer.io/hub/v1" \
        --header "Authorization: Bearer $TOKEN" \
        --header "Content-Type: application/json" \
        --data-raw "{
            \"query\" : \"mutation imageDeploy(\n    \$input: ImageDeployInput!\n  ) {\n    imageDeploy(\n      input: \$input\n    ) {\n      id\n      deploymentId\n      digest\n      env\n      labels\n      name\n      tag\n      repository\n    }\n}\",
            \"variables\" : {
                \"input\" : {
                    \"id\" : \"$IMAGE\",
                    \"tag\" : \"$TAG\",
                    \"repository\" : \"images.astronomer.cloud/$ORGANIZATION_ID/$DEPLOYMENT_ID\"
                    }
                }
            }"
```





Pipeline variables to add in Jenkins for the `build.sh` to work:
```
ASTRONOMER_KEY_ID (given when you create an API Key in Astro UI)
ASTRONOMER_KEY_SECRET (given when you create an API Key in Astro UI)
ORGANIZATION_ID (find this value by visiting: https://cloud.astronomer.io/settings)
DEPLOYMENT_ID - when on your Astro deployment UI screen, the last part of your URL, for example if your URL is https://cloud.astronomer.io/cknev9xks05093m1iv15kz01t/deployments/ckz76ezut191111fz18nhoio2z, your deployment ID will be ckz76ezut191111fz18nhoio2z
```

**Comment by paolaperaza** [comment]
Related: #182

**Comment by jwitz** [comment]
@aspain Closing this in favor of https://github.com/astronomer/docs/issues/362, which has individual sub issues for each CI/CD tool that we could support. I think the templates _will_ be different for Gen 2 based on the existing GH Actions template. Because of that, this issue needs to be a field-led effort, with engineers sending validated builds/ templates to me for publication. Do you know who might be a good first contact for getting some of these templates documented for Gen 2?

Also thanks for the Jenkins script! I'm working to get that in our docs this week.
